name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  JAVA_VERSION: '21'
  GRADLE_VERSION: '8.10'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: ${{ env.GRADLE_VERSION }}
        cache-disabled: false

    - name: Build with Gradle
      run: ./gradlew build --warning-mode all

  # Only enable this if you've enabled dependency graph in repo settings
  # dependency-submission:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up JDK ${{ env.JAVA_VERSION }}
  #     uses: actions/setup-java@v4
  #     with:
  #       java-version: ${{ env.JAVA_VERSION }}
  #       distribution: 'temurin'
  #   - name: Generate dependency graph
  #     run: ./gradlew generateDependencyGraph
